### ISSUE TITLE
feat/{ui}-menu/details

### ISSUE THREAD

**Issue by Mariusz-web** [coders-camp-2021-best-team/Freeverse#47]
**AC**

***ORGANISMS***

Should be using InformationRow

Props {onClick, children, src}

**Comment by Veryyapeee** [comment]
Generally the name of the task and description is far from accurate.

That's not detail's, I think that the items which you are describing here are the "edit profile" etc buttons.

If so (and I think that's it) there's no need for creating such a component, just no point, creating boilerplate, it's not reusable, we should just use 3 times the <InformationRow /> in menu component
